<?php
/*
 * ADOBE SYSTEMS INCORPORATED
 * Copyright 2007 Adobe Systems Incorporated
 * All Rights Reserved
 * 
 * NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance with the 
 * terms of the Adobe license agreement accompanying it. If you have received this file from a 
 * source other than Adobe, then your use, modification, or distribution of it requires the prior 
 * written permission of Adobe.
 */
//'SQL_ERROR' => 'خطای پایگاه داده. <br><div style="display:none">%s</div>',
// 'MULTIPLE_OPERATIONS_SUCCEDED' => 'عملیات باموفقیت انجام شد. <br><div style="display:none">%s</div>',

$res = array(
'ERROR_LABEL' => 'خطا:',
'UNKNOWN_TRIGGER' => 'خطای داخلی.',
'SQL_ERROR' => 'خطای پایگاه داده. <br><div style="display:none">%s</div>',
'DEL_NO_PK_SET' => 'خطای داخلی.',
'DEL_NO_PK_VAL' => 'خطای داخلی.',
'DEL_NO_RS' => 'خطای داخلی.',
'FIELDS_EVAL_EXPR_FAILED' => 'خطای داخلی.',
'FIELDS_EVAL_EXPR_INVALID' => 'خطای داخلی.',
'FIELDS_LOCAL_RS' => 'خطای داخلی.',
'FIELDS_FAKE_RS_ERROR' => 'خطای داخلی.',
'FIELDS_NO_TABLE' => 'خطای داخلی.',
'FIELDS_AFTER_UPDATE_ERROR' => 'خطای داخلی.',
'FIELDS_SAVEDATA_ERROR' => 'خطای داخلی.',
'MULTIPLE_FAKE_RS_ERROR' => 'خطای داخلی.',
'MULTIPLE_OPERATIONS_SUCCEDED' => 'عملیات باموفقیت انجام شد. <br><div style="display:none"></div>',
'MDEL_ERROR' => 'هنگام حذف اطلاعات، خطایی رخ داده است.',
'MDEL_NO_RS' => 'خطای داخلی.',
'MINS_ERROR' => 'هنگام درج اطلاعات، خطایی رخ داده است.',
'MUPD_ERROR' => 'هنگام بروزرسانی اطلاعات، خطایی رخ داده است.',
'MUPD_RS' => 'خطای داخلی.',
'UPD_NO_PK_SET' => 'خطای داخلی.',
'UPD_NO_FIELDS' => 'خطای داخلی.',
'UPD_RS' => 'خطای داخلی.',
'CHECK_TF_SQL_ERROR' => 'خطای داخلی.',
'DEL_DR_SQL_ERROR' => 'خطای داخلی.',
'EMAIL_FAILED' => 'خطا در ارسال ایمیل.',
'EMAIL_NO_TEMPLATE' => 'خطای داخلی.',
'FILE_DEL_ERROR' => 'خطای حذف فایل.',
'FILE_UPLOAD_ERROR' => 'خطای بارگذاری فایل. <br>%s',
'FILE_UPLOAD_WRONG_COLTYPE' => 'خطای بارگذاری فایل. هیچ ورودی از نوع فایل، ارائه نشده است.',
'FILE_UPLOAD_RENAME' => 'خطای بارگذاری فایل. تغییر نام فایل، امکان پذیر نیست.',
'IMG_RESIZE' => 'خطای بارگذاری تصویر. خطا در تغییر سایز تصویر.',
'LOGIN_MESSAGE_LABEL' => 'پیغام:',
'LOGIN_FAILED' => 'ورود، ناموفق بود.',
'LOGIN_INVALID_USERNAME' => 'نام کاربری نامعتبر.',
'LOGIN_INVALID_PASSWORD' => 'رمزعبور نامعتبر.',
'LOGIN_FAILED_NO_ACTIVE_FIELD' => 'خطای داخلی.',
'LOGIN_INACTIVE_USER' => 'ورود، ناموفق بود. لطفا ابتدا حساب کاربری خود را فعال نمائید.<br />برای فعال سازی حساب کاربری خود، باید روی لینک ارسال شده به شما در ایمیل فعال سازی، کلیک نمائید.',
'LOGIN_INACTIVE_USER_FIELDERR' => 'کاربر غیرفعال.',
'ACTIVATION_NOT_ENABLED' => 'خطای داخلی.',
'ACTIVATION_NO_EMAIL' => 'خطای داخلی.',
'ACTIVATION_WRONG_TABLE' => 'خطای داخلی.',
'ACTIVATION_WRONG_P' => 'خطای داخلی.',
'ACTIVATION_NO_ACTIVE_FIELD' => 'خطای داخلی.',
'ACTIVATION_NO_PARAM_RANDOM' => 'خطای فعال سازی.',
'LOGIN_RECORDSET_ERR' => 'خطای داخلی.',
'ACTIVATION_NO_PARAM_EMAIL' => 'خطای فعال سازی.',
'ACTIVATION_NO_RECORDS' => 'خطای فعال سازی.',
'ACTIVATION_TOOMANY_RECORDS' => 'خطای فعال سازی.',
'ACTIVATION_ALREADY_ACTIVE' => 'خطای فعال سازی. این حساب کاربری قبلا فعال شده است.',
'FORGOTPASS_NO_EMAIL' => 'خطای داخلی.',
'FORGOTPASS_WRONG_TABLE' => 'خطای داخلی.',
'FORGOTPASS_WRONG_PK' => 'خطای داخلی.',
'FORGOTPASS_WRONG_EMAIL' => 'خطای فراموشی رمز عبور.',
'FORGOTPASS_WRONG_EMAIL_FIELDERR' => 'آدرس ایمیل مشخص شده وجود ندارد.',
'FORGOTPASS_TOOMANY_RECORDS' => 'خطای فراموشی رمز عبور.',
'FORGOTPASS_TOOMANY_RECORDS_FIELDERR' => 'بیش از یک آدرس ایمیل یافت شده است.',
'FORGOTPASS_INACTIVE_USER' => 'خطای فراموشی رمز عبور. تغییر رمز عبور کاربران غیر فعال، امکان پذیر نمی باشد.',
'UPDATEPASS_NO_NEW_PASS' => 'لطفا رمز عبور جدید را وارد نمائید یا هر دو قسمت رمز عبور قدیمی و رمز عبور جدید را خالی بگذارید.',
'UPDATEPASS_NO_NEW_PASS_FIELDERR' => 'قسمت رمز عبور جدید خالی است.',
'UPDATEPASS_NO_OLD_PASS' => 'لطفا رمز عبور قدیمی را وارد نمائید یا هر دو قسمت رمز عبور قدیمی و رمز عبور جدید را خالی بگذارید.',
'UPDATEPASS_NO_OLD_PASS_FIELDERR' => 'قسمت رمز عبور قدیمی خالی است.',
'UPDATEPASS_NO_RECORD' => 'خطای داخلی.',
'UPDATEPASS_TOMANY_RECORDS' => 'خطای داخلی.',
'UPDATEPASS_WRONG_OLD_PASS' => 'در بروزرسانی حساب کاربری شما خطایی رخ داده است. رمز عبور قدیمی اشتباه است.',
'UPDATEPASS_WRONG_OLD_PASS_FIELDERR' => 'رمز عبور قدیمی اشتباه است.',
'LOGIN_MESSAGE__REG_ACTIVATE' => 'حساب کاربری شما ایجاد شده است. برای جزئیات فعال سازی حساب کاربری خود، ایمیلتان را بررسی نمائید.',
'LOGIN_MESSAGE__REG_EMAIL' => 'حساب کاربری شما ایجاد شده است. برای جزئیات، ایمیلتان را بررسی نمائید.',
'LOGIN_MESSAGE__REG' => 'حساب کاربری شما ایجاد شده است.',
'LOGIN_MESSAGE__ACTIVATED' => 'حساب کاربری شما فعال شده است. لطفا وارد شوید.',
'LOGIN_MESSAGE__FORGOT' => 'رمز عبور شما به ایمیلتان ارسال شد.',
'LOGIN_MESSAGE__DENIED' => 'برای دسترسی به این صفحه باید اعتبارات لازم را داشته باشید. لطفا وارد شوید.',
'REGISTRATION_UNIQUE_USER' => 'در ساخت حساب کاربری شما خطایی رخ داده است.',
'REGISTRATION_UNIQUE_USER_FIELDERR' => 'کاربر از قبل وجود دارد.',
'LOGIN_FAILED_MANYRECORDS' => 'ورود، ناموفق بود.',
'LOGIN_FAILED_MANYRECORDS_FIELDERR' => 'بیش از یک کاربر یافت شده است.',
'DEFAULT_TRIGGER_MESSAGE' => 'خطایی رخ داده است.',
// 'TRIGGER_MESSAGE__CHECK_UNIQUE' => 'اطلاعات تکراری یافت شده است. از قبل، یک رکورد یکسان در دیتابیس شما برای فیلد موردنظر وجود دارد. <br><div style="display:none">\'%s\'</div>',
'TRIGGER_MESSAGE__CHECK_UNIQUE' => 'اطلاعات تکراری یافت شده است. از قبل، یک رکورد یکسان در دیتابیس شما برای فیلد موردنظر وجود دارد.',
'TRIGGER_MESSAGE__CHECK_MASTER_RECORD' => 'بررسی رکورد اصلی انجام نشد.',
'TRIGGER_MESSAGE__CHECK_DETAIL_RECORD' => 'بررسی رکورد جزئیات انجام نشد.',
'TRIGGER_MESSAGE__THROW_ERROR' => 'خطایی رخ داده است.',
'ONLINE_TROUBLESHOOT' => 'عیب یاب خطای آنلاین',
'EMAIL_ERROR_RECORDSET' => 'خطا در ارسال ایمیل.',
'SET_ORDER_FIELD_SQL_ERROR' => 'خطا در دریافت مقدار ستون sort.',
'ERR_DOWNLOAD_FILE' => 'خطا در دانلود فایل!',
'ERR_DOWNLOAD_FILE_WRONG_HASH' => 'خطا در دانلود فایل. بررسی امنیتی انجام نشد.',
'ERR_DOWNLOAD_FILE_NO_READ' => 'خطا در دانلود فایل <br><div style="display:none">\'%s\'</div>.',
'ERR_DOWNLOAD_FILE_NO_READ_D' => 'خطا در دانلود فایل <br><div style="display:none">\'%s\'</div>.',
'ERR_DOWNLOAD_FILE_LINK_EXPIRED' => 'لینک دانلود منقضی شده است، لطفا جهت دانلود پیوست، صفحه پیوست را بروزرسانی نمایید تا لینک دانلود جدید ساخته شود.',
'IMPORT_ERROR' => 'import اطلاعات انجام نشد.',
'IMPORT_OPERATIONS_SKIPPED' => 'عملیات رد شد. <br><div style="display:none">%s</div>',
'IMPORT_SKIPPED' => 'import بعضی از اطلاعات انجام نشد.',
'IMPORT_SQL_ERROR' => 'import اطلاعات انجام نشد.',
'CSV_IMPORT_DUPLICATE_ERROR' => 'خطا.<br><div style="display:none">خط %s:<br/> - ورودی تکراری یافت شد، %s برای فیلد %s.</div>',
'CSV_IMPORT_LINE_ERROR' => 'خطا. <br><div style="display:none">خط %s:%s</div>',
'CSV_IMPORT_NO_FILE_ERROR' => 'فایل CVS ای بارگذاری نشده است.',
'CSV_HINTS_SAMPLES' => 'نمونه ها:',
'CSV_HINTS_NOTES' => 'یادداشت ها:',
'CSV_HINTS_STRING' => 'رشته',
'CSV_HINTS_TAB' => 'تب',
'CSV_HINTS_CELL_SEPARATOR' => 'جداکننده ی سلول، <strong>%s</strong> است.',
'CSV_HINTS_CELL_ENCLOSURE' => 'محفظه ی سلول <strong>%s</strong> است.',
'CSV_HINTS_DATE_FORMAT' => 'فرمت تاریخ <strong>%s</strong> است.',
'CSV_HINTS_COLUMNNAME_UNIQUE' => 'خطا.<br><div style="display:none">ستون <strong>%s</strong> باید منحصر بفرد باشد.</div>',
'CSV_HINTS_COLUMNREFERENCE_UNIQUE' => 'خطا. <br><div style="display:none">ستون <strong>#%s</strong> باید منحصر بفرد باشد</div>',
'CSV_HINTS_COLUMNS_ASSOCIATIONS' => '<strong>ارتباطات ستون ها</strong>',
'CSV_HINTS_PER_COLUMN_IMPORT' => 'خطا. <br><div style="display:none">ستون <strong>#%s</strong> در فیلد <strong>%s</strong> import شد</div>',
'XML_IMPORT_DUPLICATE_ERROR' => 'خطای ورودی تکراری<br><div style="display:none">سطر %s:<br/> - ورودی تکراری یافت شد، %s برای فیلد %s.</div>',
'XML_IMPORT_LINE_ERROR' => 'خطا.<br><div style="display:none">سطر %s:%s</div>',
'XML_IMPORT_NO_FILE_ERROR' => 'فایل XML ای بارگذاری نشده است.',
'XML_IMPORT_INVALID_XML_ERROR' => 'منبع XML نامعتبر است.',
'XML_IMPORT_READ_FILE_ERROR' => 'خواندن فایل XML امکان پذیر نمی باشد.',
'XML_IMPORT_NO_URI_ERROR' => 'مکان نامعتبر XML از راه دور.',
'XML_IMPORT_READ_URI_ERROR' => 'مکان: \'%s\' باز نشد.',
'PHP_XML_IMPORT_FOPEN_DISABLED_ERROR' => 'در وارد کردن داده های XML خطایی رخ داده است.',
'PHP_XML_IMPORT_MBSTRING_DISABLED_ERROR' => 'در وارد کردن داده های XML خطایی رخ داده است.',
'XML_HINTS_SAMPLES' => 'نمونه ها:',
'XML_HINTS_NOTES' => 'یادداشت ها:',
'XML_HINTS_STRING' => 'رشته',
'XML_HINTS_DATE_FORMAT' => 'فرمت تاریخ به صورت <strong>%s</strong> می باشد.',
'XML_HINTS_COLUMNNAME_UNIQUE' => 'خطا.<br><div style="display:none">ستون <strong>%s</strong> باید منحصر بفرد باشد.</div>',
'TRIGGER_MESSAGE__MTM_NO_REFERENCE' => 'خطای داخلی.',
'TRIGGER_MESSAGE__MTM_SQL_ERROR' => 'خطای داخلی.',
'UNKNOWN_TRIGGER_D' => 'نوع تریگر ناشناخته است.<br><div style="display:none">\'%s\'</div>',
'SQL_ERROR_D' => 'خطای پایگاه داده. <br><div style="display:none">%s.</div>',
'DEL_NO_PK_SET_D' => 'tNG_delete.prepareSQL:<br />ستون کلید اصلی تنظیم نشده است.',
'DEL_NO_PK_VAL_D' => 'tNG_delete.prepareSQL:<br />مقدار ستون کلید اصلی قرار داده نشده است.',
'FIELDS_EVAL_EXPR_FAILED_D' => 'tNG_fields.evaluateFieldExpr:<br />عبارت \'%s\' را نمی توان ارزیابی نمود.',
'FIELDS_EVAL_EXPR_INVALID_D' => 'tNG_fields.evaluateFieldExpr:<br />عبارت \'%s\' نامعتبر است.<br />از ارقام (0 تا 9) و/یا کارکترهای + - * / . ( ) استفاده نمائید.',
'FIELDS_LOCAL_RS_D' => 'tNG_fields.getLocalRecordset:<br />این روش انتزاعی بوده و باید بازنویسی شود.',
'FIELDS_FAKE_RS_ERROR_D' => 'tNG_fields.getFakeRecordset:<br />خطای پایگاه داده. <br><div style="display:none"></div>',
'FIELDS_NO_TABLE_D' => 'tNG_fields.prepareSQL:<br />لطفا برای تراکنش جاری، یک جدول تنظیم نمائید.',
'FIELDS_AFTER_UPDATE_ERROR_D' => 'tNG_fields.afterUpdateField:<br />خطای پایگاه داده. <br><div style="display:none">.</div>',
'FIELDS_SAVEDATA_ERROR_D' => 'tNG_fields.saveData:<br />خطای پایگاه داده. <br /><br><div style="display:none"><br /></div>',
'MULTIPLE_FAKE_RS_ERROR_D' => 'tNG_multiple.getFakeRecordset <br />خطای پایگاه داده. <br><div style="display:none"></div>',
'MDEL_ERROR_D' => 'خطای tNG_multipleDelete.<br />هنگام حذف اطلاعات، خطایی رخ داده است.',
'MDEL_NO_RS_D' => 'tNG_multipleDelete.getLocalRecordset:<br />تراکنش حذف متعدد، مجموعه رکوردی را صادر نمی کند.',
'MINS_ERROR_D' => 'خطای tNG_multipleInsert.<br />هنگام درج اطلاعات، خطایی رخ داده است.',
'MUPD_ERROR_D' => 'خطای tNG_multipleUpdate.<br />هنگام بروزرسانی اطلاعات، خطایی رخ داده است.',
'MUPD_RS_D' => 'tNG_multipleUpdate.getLocalRecordset:<br />خطا.<br><div style="display:none"><strong>پیغام خطا:</strong><br />%s<br /><strong>دستور پایگاه داده:</strong><br />%s.</div>',
'UPD_NO_PK_SET_D' => 'tNG_update.prepareSQL:<br />ستون کلید اصلی تنظیم نشده است.',
'UPD_NO_FIELDS_D' => 'tNG_update.prepareSQL:<br />لطفا حداقل یک فیلد را برای بروزرسانی مشخص نمائید.',
'UPD_RS_D' => 'tNG_update.getLocalRecordset:خطا.<br /><br><div style="display:none"><strong>پیغام خطا:</strong><br /><br /><strong>دستور پایگاه داده:</strong><br />%s</div>',
'CHECK_TF_SQL_ERROR_D' => 'هنگام بررسی فیلد جدول، خطایی رخ داده است.<br /><br><div style="display:none">پیغام خطا:<br /><br />دستور پایگاه داده:<br />%s</div>',
'DEL_DR_SQL_ERROR_D' => 'هنگام حذف از جدول مربوطه خطایی رخ داده است.<br /><br><div style="display:none">پیغام خطا:<br /><br />دستور پایگاه داده:<br />%s</div>',
'EMAIL_FAILED_D' => 'خطا.<br><div style="display:none"></div>',
'EMAIL_NO_TEMPLATE_D' => 'فایل قالب، باز نمی شود.',
'FILE_DEL_ERROR_D' => 'حذف فایل \'%s\' امکان پذیر نمی باشد. لطفا مجوزهای فایل را بررسی نمائید.',
'FILE_UPLOAD_ERROR_D' => 'خطای بارگذاری فایل. <br>%s',
'FILE_UPLOAD_WRONG_COLTYPE_D' => 'خطای بارگذاری فایل. <br><div style="display:none"> فیلد "" ویژگی "Submit as" تنظیم شده برای "file" را ندارد.</div>',
'FILE_UPLOAD_RENAME_D' => 'خطای بارگذاری فایل. تغییر نام فایل \'%s\' به \'%s\'، امکان پذیر نیست.',
'IMG_RESIZE_D' => 'خطای بارگذاری تصویر. خطا در تغییر سایز تصویر. <br><div style="display:none"></div>',
'LOGIN_FAILED_D' => '',
'LOGIN_FAILED_NO_ACTIVE_FIELD_D' => '<br><div style="display:none">لطفا ستون عددی \'\' را در دیتابیس، جهت اجازه ی فعال سازی اضافه نمائید.</div>',
'LOGIN_INACTIVE_USER_D' => '',
'ACTIVATION_NOT_ENABLED_D' => 'اجازه ی فعال سازی در Developer Toolbox Control Panel > Login Settings داده نشده است.',
'ACTIVATION_NO_EMAIL_D' => 'ستون ایمیل در Developer Toolbox Control Panel > Login Settings > Database, جهت اجازه ی فعال سازی حساب کاربری، تنظیم نشده است.',
'ACTIVATION_WRONG_TABLE_D' => 'فعال سازی باید روی جدول تنظیم شده در Developer Toolbox Control Panel > Login Settings > Database انجام شود.',
'ACTIVATION_WRONG_P_D' => 'ستون کلید اصلی مشخص شده با ستونی که در Developer Toolbox Control Panel > Login Settings > Database تنظیم شده، تفاوت دارد.',
'ACTIVATION_NO_ACTIVE_FIELD_D' => 'برای تراکنش فعلی، مجموعه ستون \'Active\' ، در Developer Toolbox Control Panel > Login Settings > Database باید وجود داشته باشد.',
'ACTIVATION_NO_PARAM_RANDOM_D' => 'فعال سازی نیازمند پارامتر \'kt_login_random\' URL می باشد.',
'LOGIN_RECORDSET_ERR_D' => 'خطا در ایجاد مجموعه رکورد فعال سازی.',
'ACTIVATION_NO_PARAM_EMAIL_D' => 'فعال سازی نیازمند پارامتر \'kt_login_email\' URL می باشد.',
'ACTIVATION_NO_RECORDS_D' => 'اطلاعاتی مطابق با ضوابط یافت نشد.',
'ACTIVATION_TOOMANY_RECORDS_D' => 'اطلاعات بیشتری مطابق با ضوابط یافت شد.',
'ACTIVATION_ALREADY_ACTIVE_D' => '',
'FORGOTPASS_NO_EMAIL_D' => 'جهات اجازه ی بازیابی رمز عبور، ستون ایمیل باید در Developer Toolbox Control Panel > Login Settings > Database تنظیم شود.',
'FORGOTPASS_WRONG_TABLE_D' => 'در جدول تنظیم شده در Developer Toolbox Control Panel > Login Settings > Database، بازیابی رمزعبور باید انجام شود',
'FORGOTPASS_WRONG_PK_D' => 'ستون کلید اصلی مشخص شده با ستون تنظشیم شده در Developer Toolbox Control Panel > Login Settings > Database تفاوت دارد.',
'FORGOTPASS_WRONG_EMAIL_D' => '',
'FORGOTPASS_TOOMANY_RECORDS_D' => '',
'FORGOTPASS_INACTIVE_USER_D' => '',
'UPDATEPASS_NO_NEW_PASS_D' => '',
'UPDATEPASS_NO_OLD_PASS_D' => '',
'UPDATEPASS_NO_RECORD_D' => 'رکورد مشخص شده وجود ندارد.',
'UPDATEPASS_TOMANY_RECORDS_D' => 'بیش از یک رکورد یافت شد.',
'UPDATEPASS_WRONG_OLD_PASS_D' => '',
'LOGIN_FAILED_MANYRECORDS_D' => '',
'DEFAULT_TRIGGER_MESSAGE_D' => 'خطایی رخ داده است.',
'TRIGGER_MESSAGE__CHECK_UNIQUE_D' => '',
'TRIGGER_MESSAGE__CHECK_MASTER_RECORD_D' => 'بررسی رکورد اصلی انجام نشد.',
'TRIGGER_MESSAGE__CHECK_DETAIL_RECORD_D' => 'بررسی رکورد جزئیات انجام نشد.',
'TRIGGER_MESSAGE__THROW_ERROR_D' => 'خطایی رخ داده است.',
'EMAIL_ERROR_RECORDSET_D' => 'مجموعه رکورد معتبری با نام %s یافت نشد.',
'SET_ORDER_FIELD_SQL_ERROR_D' => 'خطا در دریافت مقدار ستون sort.<br /><br><div style="display:none">خطای پایگاه داده: <br />%s<br />%s</div>',
'IMPORT_ERROR_D' => '',
'IMPORT_SKIPPED_D' => '',
'IMPORT_SQL_ERROR_D' => 'فیلد منحصر بفرد بررسی نشد. <br><div style="display:none">%s</div>',
'CSV_IMPORT_DUPLICATE_ERROR_D' => '',
'CSV_IMPORT_LINE_ERROR_D' => '',
'CSV_IMPORT_NO_FILE_ERROR_D' => '',
'CSV_HINTS_SAMPLES_D' => '',
'CSV_HINTS_NOTES_D' => '',
'CSV_HINTS_STRING_D' => '',
'CSV_HINTS_TAB_D' => '',
'CSV_HINTS_CELL_SEPARATOR_D' => '',
'CSV_HINTS_CELL_ENCLOSURE_D' => '',
'CSV_HINTS_DATE_FORMAT_D' => '',
'CSV_HINTS_COLUMNNAME_UNIQUE_D' => '',
'CSV_HINTS_COLUMNREFERENCE_UNIQUE_D' => '',
'CSV_HINTS_COLUMNS_ASSOCIATIONS_D' => '',
'CSV_HINTS_PER_COLUMN_IMPORT_D' => '',
'XML_IMPORT_DUPLICATE_ERROR_D' => '',
'XML_IMPORT_LINE_ERROR_D' => '',
'XML_IMPORT_NO_FILE_ERROR_D' => '',
'XML_IMPORT_INVALID_XML_ERROR_D' => 'خطا <br><div style="display:none">خطای %s در خط %s.</div>',
'XML_IMPORT_READ_FILE_ERROR_D' => '',
'XML_IMPORT_NO_URI_ERROR_D' => '',
'XML_IMPORT_READ_URI_ERROR_D' => '',
'PHP_XML_IMPORT_FOPEN_DISABLED_ERROR_D' => 'باز نمودن URL از راه دور مجاز نمی باشد. \'allow_url_fopen\' را در php.ini فعال نمائید.',
'PHP_XML_IMPORT_MBSTRING_DISABLED_ERROR_D' => 'تبدیل های مجموعه کارکترها انجام پذیر نمی باشد. پسوند \'mbstring\' را فعال نمائید.',
'XML_HINTS_SAMPLES_D' => '',
'XML_HINTS_NOTES_D' => '',
'XML_HINTS_STRING_D' => '',
'XML_HINTS_DATE_FORMAT_D' => '',
'XML_HINTS_COLUMNNAME_UNIQUE_D' => '',
'TRIGGER_MESSAGE__MTM_NO_REFERENCE_D' => 'مرجع کلید خارجی موجود نمی باشد.',
'TRIGGER_MESSAGE__MTM_SQL_ERROR_D' => 'ManyToMany خطای پایگاه داده  <br><div style="display:none">%s</div><br /> <br><div style="display:none">پایگاه داده: %s</div>.',
'ERROR_TIDY_CONTENT' => 'خطا در تبدیل به XHTML. هنگام تلاش برای اجرای HTML Tidy خطایی رخ داده است!',
'ERROR_TIDY_CONTENT_D' => 'خطا در تبدیل به XHTML. هنگام تلاش برای اجرای HTML Tidy خطایی رخ داده است!  <br><div style="display:none">%s</div>',
);
?>